name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use API key in script
        env:
          API_KEY: ${{ secrets.API_key1 }}  # Henter din API-nøgle fra secrets
        run: |
          echo "Using API key for API call"
          curl -H "Authorization: Bearer $API_KEY" https://api.example.com/endpoint
